[project]
name = "chainit"
version = "0.1.0"
description = "Lightweight pipeline utilities"
requires-python = ">=3.12"
dependencies = ["numpy", "cffi"]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
