[project]
name = "chainit"
version = "0.1.0"
description = "Lightweight pipeline utilities with optional FFI acceleration"
requires-python = ">=3.12"
dependencies = ["numpy", "cffi", "maturin>=1"]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
